"""Updated my tables

Revision ID: 01d739e72c7e
Revises: 267edd3693ae
Create Date: 2024-04-15 02:10:13.247001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d739e72c7e'
down_revision = '267edd3693ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.alter_column('sweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_vendor_sweets_vendor_id_vendors', type_='foreignkey')
        batch_op.drop_constraint('fk_vendor_sweets_sweet_id_sweets', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vendor_sweets_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_vendor_sweets_sweet_id_sweets'), 'sweets', ['sweet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vendor_sweets_sweet_id_sweets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_vendor_sweets_vendor_id_vendors'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vendor_sweets_sweet_id_sweets', 'sweets', ['sweet_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_vendor_sweets_vendor_id_vendors', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
