"""Table upgrade

Revision ID: 267edd3693ae
Revises: 9898ff8defb4
Create Date: 2024-04-15 01:19:35.558411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267edd3693ae'
down_revision = '9898ff8defb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.alter_column('sweet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_sweets', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sweet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
